# Generated by Django 4.0.4 on 2022-06-05 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('title', models.CharField(blank=True, default='Summary of Monthly Budgeted Expenses', max_length=150, verbose_name='Title')),
                ('pie_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pie Title')),
                ('persistent', models.BooleanField(default=False, verbose_name='Persistent')),
                ('surplus_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Surplus Weekly')),
                ('surplus_bi_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Surplus BeWeekly')),
                ('surplus_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Surplus Monthly')),
                ('surplus_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Surplus Yearly')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='budget.category')),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_budgets', to='budget.category')),
            ],
        ),
    ]
