# Generated by Django 4.0.5 on 2022-06-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='category',
            name='c_type',
            field=models.IntegerField(choices=[(1, 'INCOME'), (2, 'EXPENSE'), (3, 'OTHERS')], default=3, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='category',
            name='persistent',
            field=models.BooleanField(default=False, verbose_name='Persistent'),
        ),
        migrations.AddField(
            model_name='category',
            name='total_bi_weekly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Total Bi-Weekly'),
        ),
        migrations.AddField(
            model_name='category',
            name='total_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Total Monthly'),
        ),
        migrations.AddField(
            model_name='category',
            name='total_weekly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Total Weekly'),
        ),
        migrations.AddField(
            model_name='category',
            name='total_yearly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Total Yearly'),
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('weekly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Weekly Net')),
                ('bi_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Bi-Weekly Net')),
                ('monthly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Monthly Net')),
                ('yearly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Yearly Net')),
                ('ref_category', models.BigIntegerField(blank=True, null=True, verbose_name='Ref Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.category')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
