# Generated by Django 4.0.4 on 2022-06-03 11:49

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_city_profile_country_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(users.utils.Genders['Male'], 1), (users.utils.Genders['Female'], 2), (users.utils.Genders['Others'], 3)], max_length=255),
        ),
    ]
