# Generated by Django 4.0.4 on 2022-06-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_gender_name_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender_name',
        ),
    ]
